source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'QHTextFieldDemo' do

  pod 'QHTextField', :path => '../QHTextField.podspec'
  pod 'IQKeyboardManager'
  pod 'MBProgressHUD'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ='8.0'
            end
        end
    end

end
